import React from "react";
import { PrimaryButton } from "../../../components/Button";
import { useModal } from "../useModal";
import { Card, CardHeader, CardBody } from "../../../components/Card";
import { Modal } from "../Modal";

export default {
  title: "Widgets/Modal",
  argTypes: {},
};

const BigModal = () => (
  <Modal centered={true}>
    <Card>
      <CardHeader>Sorry for being to loooong</CardHeader>
      <CardBody>
        Unifi Protocol is a group of non-custodial, interoperable,
        decentralized, and multi-chain smart contracts providing the building
        blocks for the next generation of DeFi development. Unifi provides a
        bridge to connect the existing economy of Ethereum-based DeFi products
        to growing DeFi markets on other blockchains. Unifi utilizes the time
        tested SEED Bridge to connect any Ethereum or EVM/NVM-based DeFi
        products to other blockchains. The Unlimited Potential Token (UP) is at
        the core of Unifi’s DeFi system. UP minting occurs in direct proportion
        to the fees and other revenue generated by the entire Unifi Protocol.
        This includes designated fees or revenue from all Unifi-developed
        platforms, as well as from any projects developed by others which
        utilize Unifi Protocol. The minting process is designed to ensure the
        redemption value of all UP tokens must go UP every time a new UP token
        is minted. UP token creates a very unique and lucrative rewards
        structure for all holders, protocol users, and liquidity providers.
        Unifi Protocol is designed around a decentralized autonomous
        organization (DAO) governed via a decentralized governance token. The
        following are highlights taken from the full Unifi Protocol whitepaper.
        The complete white paper is available here: Unifi White Paper
        Introducing Unifi Protocol Unifi Protocol unifies the multi-chain DeFi
        world through the SEED Bridge. This allows Unifi to be a multi-chain and
        non-custodial decentralized swap and complete DeFi protocol. Unifi
        Protocol features incentivized liquidity pooling, a fee sharing
        governance token, loyalty rewards token, lending platform, and
        cross-chain swap interoperability. Unifi was developed by Sesameseed,
        the multi-chain staking community committed to bringing their innovative
        technology solutions to all their represented blockchains. Unifi
        Protocol adds value to each blockchain upon which it is deployed,
        allowing developers to build a range of products and services around the
        smart contract based building blocks of the protocol. What is uTrade
        (and how does it relate to Unifi)? uTrade is a trading platform built
        utilizing Unifi Protocol. uTrade operates as a decentralized, unlimited
        liquidity market maker, where one token is exchanged for another,
        utilizing liquidity provided by incentivized liquidity providers. Why is
        uTrade better than existing trading platforms? Liquidity providers share
        a portion of the revenue generated by the entire Unifi Protocol, and are
        not limited to a share of fees earned solely from a specific trading
        pair. Even after liquidity is withdrawn, liquidity providers continue to
        share in fees as long as they hold UP tokens. Traders are refunded a
        portion of their trading fees in SEED and enjoy all the benefits of
        holding SEED such as daily compounding. uTrade is the only platform to
        offer a trading rebate which automatically stakes on multiple
        blockchains and earns increasing rewards. Enabled by the power of the
        SEED Bridge, uTrade will allow for the non-custodial trading of tokens
        from different blockchains. More information on UP Token Each blockchain
        where Unifi Protocol operates will have a designated base token in which
        fees and revenue is collected. For example these will be ONG on
        Ontology, ONE on Harmony, and TRX on Tron. The redemption value of UP
        tokens is the amount of base tokens Unifi Protocol will return in
        exchange for the UP token. During the UP minting process, an amount of
        base tokens (normally a percentage) are dedicated to raising the
        redemption value of all previously minted UP tokens. This amount of base
        tokens is known as the Power UP Rate (PUR). This redemption value of UP
        is verifiable on-chain, and increases every time new UP token is minted.
      </CardBody>
    </Card>
  </Modal>
);

export const BigContent = () => {
  const [open] = useModal({ component: BigModal });

  return (
    <>
      <h1>Big content Modal</h1>
      <PrimaryButton onClick={open}>Open it</PrimaryButton>
    </>
  );
};
